spring:
  application:
    name: api-gateway

server:
  port: 4000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    provider-service:
      path: /hello-service/**
      serviceId: eureka-provider
